name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1 * *' # Monthly

jobs:
  # linux:
    # name: Linux-x86
    # runs-on: ubuntu-18.04
    # env:
      # CONFIGURATION: release
    # steps:
      # - name: Checkout
        # uses: actions/checkout@v3
      # - name: Update sources to include xenial main
        # run: sudo su -c "echo 'deb http://dk.archive.ubuntu.com/ubuntu/ xenial main' >> /etc/apt/sources.list"
      # - name: Update sources to include xenial universe
        # run: sudo su -c "echo 'deb http://dk.archive.ubuntu.com/ubuntu/ xenial universe' >> /etc/apt/sources.list"
      # - name: Update packages
        # run: sudo apt update -y
      # - name: Install make
        # run: sudo apt-get install make
      # - name: Install g++-4.8
        # run: sudo apt install g++-4.8 gcc-4.8 -y
      # - name: Install headers
        # run: sudo apt-get install gcc-4.8-multilib g++-4.8-multilib -y
      # - name: Build
        # run: cd src/dmc/dlls && make -f Makefile
      # - name: Deploy
        # uses: actions/upload-artifact@v3
        # with:
          # name: Linux-x86
          # path: src/dmc/dlls/agdmc_i386.so
  win32:
    name: Win32
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install Visual C++ 6.0
      run: |
        git clone --depth 1 https://github.com/SmileyAG/MSVC600
    - name: Build
      shell: cmd
      run: |
        call MSVC600/VC98/Bin/vcvars32.bat
        msdev src/dmc/dlls/dmc.dsw /make "dmc - Win32 Release"
    - name: Upload arficacts
      uses: actions/upload-artifact@v3
      with:
        name: Win32
        path: src/dmc/dlls/agdmc.dll
